# CSVTU April-May(2023)

Question2 (d):
np.average() vs. np.mean() 

flatten and ravel functions in NumPy

Ans.  The np.mean() method returns the arithmetic mean, but the np.average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average.

- The term "mean" often refers to the "arithmetic mean", which is the sum of a set of numbers divided by the total number of the numbers in the set.
- The term "average" refers to a variety of computations, the "arithmetic mean" is one of them. Other terms include 'median,' 'mode,' 'weighted mean,' 'interquartile mean,' and a variety of others.

In [1]:
import numpy as np

temp = 0
array = np.arange(15)
print("Array:\n", array)
print("Mean of the array: ", np.mean(array))

Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Mean of the array:  7.0


In [2]:
orginal_array = np.arange(15)
weight = np.arange(15, 0, -1)

print('Original array:\n', orginal_array)
print('weight: ', weight, '\n')
print('origianl_array*weight: ', orginal_array*weight, '\n')
print('Sum of origianl_array*weight: ', np.sum(orginal_array*weight), '\n')
print('average when no weights were specified: ',np.average(orginal_array), '\n')
print('average when weights were specified: ',np.average(orginal_array,weights=weight), '\n')


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
weight:  [15 14 13 12 11 10  9  8  7  6  5  4  3  2  1] 

origianl_array*weight:  [ 0 14 26 36 44 50 54 56 56 54 50 44 36 26 14] 

Sum of origianl_array*weight:  560 

average when no weights were specified:  7.0 

average when weights were specified:  4.666666666666667 



Weighted mean = (original_array*sum(weights))/sum(weights)

**Note:** If the weight parameter is default(i.e. none), average() also returns the arithmetic mean

Difference between np.average() and np.mean()
- Many more arguments, such as dtype, out, where, and others, are available in the np.mean() method that is not accessible in the np.average() function.
- If the weights option is specified, the np.average() function may compute a weighted mean, but np.mean() cannot.
- Since np.average does not take into consideration boolean masks, it will compute the average over the entire collection of data. While the np.mean() method takes into account boolean masks, compute the mean solely across unmasked data.

**Conclusion**

- The algebraic mean of a NumPy array may be calculated using the numpy.mean() or numpy.average() functions.
- To compute the weighted algebraic mean, we may use numpy.average().
- We may utilize the dtype argument of the numpy.mean() method to compute the precise value of arithmetic mean.
- numpy.average() ignores boolean masks and computes the average across the full set of data. While the numpy.mean() function takes boolean masks into consideration, compute the mean only over unmasked data

## ravel and flatten

ravel is used to convert a 2D array into 1D array.

flatten also changes the 2D array to 1D but not in the original array and returns copy of the original array.

Differences between Flatten() and Ravel()


|ravel()|flatten()|
|-------|---------|
|Return only reference/view of the original array|Return copy of the original array|
|If you modify the array you would notice that the value of the original array also changes.|If you modify any value of this array value of the original array is not affected.|
|Ravel is faster than flatten() as it does not occupy any memory.|Flatten() is comparatively slower than ravel() as it occupies memory.|
|Ravel is a library-level function.|Flatten is a method of an ndarray object.|

In [3]:
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

# Convert nd array to 1D array
c = a.flatten()

# Flatten passes copy of
# original array to 'c'
print ("\nFlatten array using flatten: ", c)

Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten:  [1 2 3 4 3 1 4 2]


In [4]:
c[2] = 33

print ("Flatten array: ", c)

# Let's print the array a
print ("\nOriginal array:\n ", a)

Flatten array:  [ 1  2 33  4  3  1  4  2]

Original array:
  [[1 2 3 4]
 [3 1 4 2]]


In [5]:
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])

# Let's print the array a
print ("Original array:\n ", a)

ra = np.ravel(a)
print ("\nFlatten array using ravel: ", ra)


Original array:
  [[1 2 3 4]
 [3 1 4 2]]

Flatten array using ravel:  [1 2 3 4 3 1 4 2]


In [6]:
ra[3] = 44

print ("Flatten array: ", ra)

# Let's print the array a
print ("\nOriginal array:\n ", a)


Flatten array:  [ 1  2  3 44  3  1  4  2]

Original array:
  [[ 1  2  3 44]
 [ 3  1  4  2]]


Question3:

a. What do you mean by reindexing in pandas? Create a series using dict in pandas

In [7]:
# reindexing in pandas(2 marks)
import pandas as pd
series = pd.Series([2,4,6,8,10], index=['two', 'four', 'six', 'eight', 'ten'])
series

two       2
four      4
six       6
eight     8
ten      10
dtype: int64

In [8]:
series.reindex(['one', 'two', 'three', 'four'])

one      NaN
two      2.0
three    NaN
four     4.0
dtype: float64

During this operation of reindexing, it is therefore possible to change the order of the sequence of indexes,
delete some of them, or add new ones. In the case of a new label, pandas add NaN as corresponding value.

In [9]:
# changing sequence of the values w.r.t. their respective index

series.reindex(['one', 'four', 'three', 'two'])

one      NaN
four     4.0
three    NaN
two      2.0
dtype: float64

In [10]:
# series using dict in pandas

Dict = {1: 'ram', 2: 'shyam', 3: 'geeta', 4: 'lakshmi'}
Dict

{1: 'ram', 2: 'shyam', 3: 'geeta', 4: 'lakshmi'}

In [11]:
pd.Series(Dict)

1        ram
2      shyam
3      geeta
4    lakshmi
dtype: object

b. Expain how to create empty dataframe in pandas. Explain the different ways to create data frames in pandas.

In [12]:
Dict = {}
Dict
print('empty data frame')


{}