In [2]:
import numpy as np

WAP to  demonstrate different ways of creating numpy arrays

1. array()
2. arange()
3. linspace()
4. zeros()
5. ones()
6. random.rand()

In [2]:
my_array = np.array([1,2,3,4,5])
print(my_array)

[1 2 3 4 5]


In [3]:
my_array = np.array(["Hello", "World", "!"])
print(my_array)

['Hello' 'World' '!']


In [5]:
my_array = np.zeros((3,4))
my_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
my_array = np.ones((3,4))
my_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
my_array = np.arange(16)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.random.rand(10)

array([0.06399888, 0.60484219, 0.23996918, 0.76591805, 0.14703285,
       0.66863623, 0.57884318, 0.54266985, 0.79886298, 0.79105136])

WAP to demonstrate all basic operations on numpy array

In [13]:
# arithmetic operations

array1 = np.arange(1, 6)
print("array1: ", array1)
array2 = np.arange(6, 11)
print("array2:", array2)

print("addition: ", array1+array2)
print("subtraction: ", array2-array1)
print("multiplication: ", array1*array2)
print("division: ", array2/array1)

array1:  [1 2 3 4 5]
array2: [ 6  7  8  9 10]
addition:  [ 7  9 11 13 15]
subtraction:  [5 5 5 5 5]
multiplication:  [ 6 14 24 36 50]
division:  [6.         3.5        2.66666667 2.25       2.        ]


In [16]:
# reciprocal 

array1 = np.array([1,2,3,4,5], dtype='float')
np.reciprocal(array1)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [18]:
# power

arr = np.arange(1,6)
pow_arr = np.power(arr, 2)
print("pow_arr", pow_arr)

arr2 = np.arange(6, 11)
print("pow_arr2: ", np.power(arr2, arr))

pow_arr [ 1  4  9 16 25]
pow_arr2:  [     6     49    512   6561 100000]


In [19]:
# modulus

arr = np.arange(1,6)
arr2 = np.array([6, 7, 8, 9, 10])
np.mod(arr2, arr)

array([0, 1, 2, 1, 0])

WAP to demonstrate indexing, slicing and iteration on numpy array

In [20]:
array1 = np.array([1,2,3,4,5])

#indexing
print(arr[0])
print(arr[2])

1
3


In [22]:
# slicing
print(arr[1:3])
print(arr[5:1:-2])
print(arr[5:0:-1])

[2 3]
[5 3]
[5 4 3 2]


In [23]:
# iteration
for i in arr: 
    print(i)

1
2
3
4
5


In [6]:
# for 2D array
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
#indexing
print(arr2[0,0])
print(arr2[1, 2])


[[1 2 3]
 [4 5 6]]
1
6


In [10]:
#slicing
# slicing syntax for 2D slicing:- a[row range, col range]
print(arr2[0:1, 1:3])
print(arr2[:2])
print(arr2[1:3, :1])

#iteration
for i in arr2:
    print(i)

[[2 3]]
[[1 2 3]
 [4 5 6]]
[[4]]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


WAP to demonstrate the condition  and boolean array

In [12]:
a = np.arange(10, 50).reshape(8, 5)
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [13]:
# obtaining a boolean array

a>30

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [14]:
# condition array

a[a<30]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

WAP to demonstrate the shape manipulation

In [15]:
array1 = np.arange(1, 16)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
array1.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
array1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [31]:
b = np.arange(16)
c = b.reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.ravel(c)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
c.shape = (16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
c.shape = (2,8)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

WAP to demonstrate the concept of vectorization

**Vectorization:** It is the process of performing the mathematical operations on the numpy array without the explicit use of loop.

In [36]:
array1 = np.arange(5)
array1

array([0, 1, 2, 3, 4])

In [37]:
# vectorization

array1+10

array([10, 11, 12, 13, 14])

In [38]:
array1*3

array([ 0,  3,  6,  9, 12])

WAP to demonstrate the concept of broadcasting

**Broadcasting:** If two or more arrays do not have exactly the same shape but their dimensions are compatible
then the smaller array is extended or broadcasted in such a way that its size becomes equal to 
the bigger array. This whole process is called **broadcasting**.

### Constraints of broadcasting:

1. Two arrays may be subjected to broadcasting when all their dimensions are compatible if:
  
  i. the length of each dimension of two arrays must be either equal or,
  
  ii. one of the dimensions must be 
     equal to '1'.
    
2. If the two arrays are compatible for broadcasting then the size of the smaller array is extended so 
   that its size should become equal to the size of the bigger array.

In [40]:
A = np.arange(16).reshape(4,4)
B = np.arange(0, 4)
print("A: ", A)
print("B: ", B)

A:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
B:  [0 1 2 3]


In [41]:
# broadcasting

A+B

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

WAP to read tabular data from a CSV file into a structured array and print it on the screen .  

creating a csv file(student.csv): 

rollno, name, percent

101, "Ram", 67.5

102, "Shyam", 88.5

103, "Aryan", 87.4

In [42]:
data = np.genfromtxt("C:\\Users\\Aditya Mithar\\Desktop\\KP programming\\Python\\Numpy\\student.csv", delimiter=',', names=True)
data

array([(101., nan, 67.5), (102., nan, 88.5), (103., nan, 87.4)],
      dtype=[('rollno', '<f8'), ('name', '<f8'), ('percent', '<f8')])

**NOTE:** The genfromtxt() method always returns the file in form of structured array.