## Braodcasting in Python

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
a.shape

(4, 4)

In [4]:
a = np.arange(1,17).reshape(4,4)

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [6]:
a.ndim

2

In [7]:
a.size

16

In [8]:
a.shape

(4, 4)

In [9]:
a.data

In [10]:
b = np.arange(4)
b

array([0, 1, 2, 3])

# Broadcasting

If two or more arrays do not have exactly the same shape but their dimensions are compatible
then the smaller arrayis extended or broadcasted in such a way that its size becomes equal to 
the bigger array. This whole process is called **broadcasting**.

In [11]:
# Broadingcasting

c = a+b
c

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19]])

# Constraints of broadcasting:

1. Two arrays may be subjected to broadcasting when all their dimensions are compatible if:
  
  i. the length of each dimension of two arrays must be either equal or,
  
  ii. one of the dimensions must be 
     equal to '1'.
    
2. If the two arrays are compatible for broadcasting then the size of the smaller array is extended so 
   that its size should become equal to the size of the bigger array.

 # Note: 

Performing any mathematical operations on the entire array without the use of loop is called as **vectorization**.

In [12]:
d = np.arange(1,5).reshape(2,2)
print(d)

[[1 2]
 [3 4]]


In [13]:
x = a+d

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

*rule 1 of broadcasting is not  satisfied for x*

In [ ]:
u = np.arange(6).reshape(3,1,2)
u

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [ ]:
v = np.arange(6).reshape(3,2,1)
v

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [ ]:
z = u+v
z

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [ ]:
m = np.arange(1,4)
m+10

array([11, 12, 13])

# Structured Array

Structured array is that array whose each element is structure itself.

In [ ]:
starray = np.array([(101,"Ram",96.4), (105,"Ashu",85.6), (109, "Shyam", 67.9)], dtype=('i2, a10, f2'))
starray

array([(101, b'Ram', 96.4), (105, b'Ashu', 85.6), (109, b'Shyam', 67.9)],
      dtype=[('f0', '<i2'), ('f1', 'S10'), ('f2', '<f2')])

In [ ]:
starray = np.array([(101,"Ram",96.4), (105,"Ashu",85.6), (109, "Shyam", 67.9)], dtype=('int32, a10, float32'))
starray

array([(101, b'Ram', 96.4), (105, b'Ashu', 85.6), (109, b'Shyam', 67.9)],
      dtype=[('f0', '<i4'), ('f1', 'S10'), ('f2', '<f4')])

In [ ]:
starray[0]

(101, b'Ram', 96.4)

In [ ]:
starray[1]

(105, b'Ashu', 85.6)

In [ ]:
starray[2]

(109, b'Shyam', 67.9)

# Reading and Writing Array Data on Files

In [16]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.save("C:\\Users\\Aditya Mithar\\Desktop\\KP programming\\Python\\Numpy\\file_handlling.txt", a)

In [24]:
np.save("C:\\Users\\Aditya Mithar\\Desktop\\KP programming\\Python\\Numpy\\array1", a)

In [29]:
myarray = np.load("C:\\Users\\Aditya Mithar\\Desktop\\KP programming\\Python\\Numpy\\array1.npy")

In [30]:
myarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Reading File with Tabular Data

In [31]:
data = np.genfromtxt("C:\\Users\\Aditya Mithar\\Desktop\\KP programming\\Python\\Numpy\\student.csv", delimiter=',', names=True)

In [32]:
data

array([(101., nan, 67.5), (102., nan, 88.5), (103., nan, 87.4)],
      dtype=[('rollno', '<f8'), ('name', '<f8'), ('percent', '<f8')])

**Note:** the *genfromtxt()* method always returns the file in form of structured array