In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int32')

use the ndim attribute for getting the axes, the
size attribute to know the array length, and the shape attribute to get its shape.

In [5]:
a.ndim

1

In [6]:
a.size

5

In [7]:
a.shape

(5,)

# 2D array

In [17]:
b = np.array([[1.1, 2.3, 3.4, 4.5, 5.6], [9.2, 8.6, 7.2, 6.4, 0.5]])
b

array([[1.1, 2.3, 3.4, 4.5, 5.6],
       [9.2, 8.6, 7.2, 6.4, 0.5]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.dtype

dtype('float64')

In [11]:
b.ndim

2

In [12]:
b.size

10

In [15]:
b.shape

(2, 5)

In [18]:
# Another important attribute is "itemsize", which can be used with ndarray objects. It defines the size
# in bytes of each item in the array

b.itemsize

8

In [19]:
a.itemsize

4

In [20]:
# "data" is the buffer containing the actual elements of the array. This
# attribute is still not generally used, since to access the data within the array you will use the indexing

b.data

In [21]:
a.data

# Creating a numpy array
1. using array(): 
The array() function in addition to the lists can accept even tuples and sequences of tuples and also, even sequences of tuples and lists interconnected make no difference.

In [25]:
# passing tuple to array() method

c = np.array(((1,2,3), (4,5,5)))
c

array([[1, 2, 3],
       [4, 5, 5]])

In [26]:
# passing sequence of tuple and list interconnected to array()

d = np.array([(1,2,3), [4,5,6], [7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
d.dtype

dtype('int32')

In [28]:
d.ndim

2

In [29]:
d.size

9

In [30]:
d.shape

(3, 3)

Numpy array can contain any type of data including int, float, bool, string etc.

In [31]:
g = np.array([['a', 'b'], ['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [32]:
g.dtype

dtype('<U1')

In [33]:
g.dtype.name

'str32'

The dtype option

In [36]:
# using the dtype option in array() method
# explicitly define the array with complex values

f = np.array([[1,2,3], [4,5,6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

# Intrinsic creation of array

The NumPy library provides a set of functions that generate the ndarrays with an initial content, created with
some different values depending on the function.

The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape
argument while the ones() function creates an array full of ones in a very similar way.

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# arange() fucntion

This function generates NumPy arrays with numerical sequences that
respond to particular rules depending on the passed arguments. For example, if you want to generate a
sequence of values between 0 and 10, you will be passed only one argument to the function, that is the value
with which you want to end the sequence.

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# If instead of starting from zero you want to start from another value, simply specify two arguments: the
# first is the starting value and the second is the final value.

np.arange(4,10)

array([4, 5, 6, 7, 8, 9])