# Basic Operations:-

1. **Arithmetic Operators:**

In [1]:
import numpy as np

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [3]:
a*5

array([ 0,  5, 10, 15])

In [4]:
a-2

array([-2, -1,  0,  1])

In [5]:
a/2

array([0. , 0.5, 1. , 1.5])

In [6]:
a//2

array([0, 0, 1, 1], dtype=int32)

In [7]:
a+5

array([5, 6, 7, 8])

In [8]:
a

array([0, 1, 2, 3])

In [9]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [10]:
a+b

array([ 4,  6,  8, 10])

In [11]:
a-b

array([-4, -4, -4, -4])

In [12]:
a*b

array([ 0,  5, 12, 21])

In [13]:
a/b

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [14]:
a//b

array([0, 0, 0, 0])

Moreover, these arithmetic operators are also available for functions, provided that the value returned is a NumPy array. For example, you can multiply the array with the sine or the square root of the elements of the array b.

In [15]:
a*np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [16]:
a*np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

Moving on to the multidimensional case, even here the arithmetic operators continue to operate
element-wise.


In [17]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
B = np.ones((3,3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
A*B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

# The Matrix Product

The choice of operating element-wise is a peculiar aspect of the NumPy library. In fact in many other tools for data analysis, the * operator is understood as matrix product when it is applied to two matrices. Using NumPy, this kind of product is instead indicated by the dot() function. This operation is not element-wise.

In [20]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

An alternative way to write the matrix product is to see the dot() function as an object’s function of one of the two matrices.


In [21]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

**Note:** Since the matrix product is not a commutative operation, then the order of the
operands is important. Indeed A * B is not equal to B * A.


In [22]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

**2.Increment and Decrement operators**

Actually, there is no such operators in Python, since there are no operators ++ or ––. To increase or decrease the values you have to use operators such as += or –=. These operators are not different from those that we saw earlier, except that instead of creating a new array with the results, they will reassign the results to the same array.


In [23]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [24]:
a += 1
a

array([1, 2, 3, 4])

In [25]:
a -= 1
a

array([0, 1, 2, 3])

In [26]:
a *= 2
a

array([0, 2, 4, 6])

Therefore, the use of these operators is much more extensive than the simple incremental operators
that increase the values by one unit, and then they can be applied in many cases. For instance, you need
them every time you want to change the values in an array without generating a new one.


# Universal Functions(ufunc):

A universal function, generally called ufunc, is a function operating of an array in an element-by-element
fashion. This means that it is a function that acts individually on each single element of the input array to
generate a corresponding result in a new output array. At the end, you will obtain an array of the same size of
the input.

There are many mathematical and trigonometric operations that meet this definition, for example, the
calculation of the square root with sqrt(), the logarithm with log(), or the sin with sin().

In [28]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [29]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [30]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Aggregate Functions:

Aggregate functions are those functions that perform an operation on a set of values, an array for example,
and produce a single result. Therefore, the sum of all the elements in an array is an aggregate function. 
Many
functions of this kind are implemented within the class ndarray.

In [34]:
a = np.arange(1,16,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [35]:
a.sum()

64

In [38]:
# np.sum(a)
np.ndarray.sum(a)

64

In [39]:
a.max()

15

In [40]:
a.min()

1

In [42]:
#standard deviation
a.std()

4.58257569495584

In [43]:
a.mean()

8.0