# Indexing, Slicing and Iterating

In [1]:
import numpy as np

In [2]:
a = np.arange(4,16,2)
a

array([ 4,  6,  8, 10, 12, 14])

In [3]:
#accessing elements through index
a[4]

12

In [4]:
a[-3]

10

To select multiple items at once, you can pass array of indexes within the square brackets

In [5]:
a[[2,4,5]]

array([ 8, 12, 14])

**Indexing of 2D array

In [6]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b[1,1]

5

In [8]:
b[2,1]

8

In [9]:
# to access multiple element at once, syntax: 
# array_name[[set of row values separted by commas],[set of column values separted by commas]]

b[[1,2],[1,2]]

array([5, 9])

# Slicing

Slicing is the operation which allows you to extract portions of an array to generate new ones. Whereas
using the Python lists the arrays obtained by slicing are copies, in NumPy, arrays are views onto the same
underlying buffer.

In [12]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [13]:
a[1:5]

array([11, 12, 13, 14])

In [17]:
a[1:5:2]

array([11, 13])

In [18]:
a[::2]

array([10, 12, 14])

In [19]:
a[:5:2]

array([10, 12, 14])

In [20]:
a[:5:]

array([10, 11, 12, 13, 14])

In [21]:
a[::-1]

array([15, 14, 13, 12, 11, 10])

In [22]:
a[:-4:]

array([10, 11])

In [25]:
a[-1::]

array([15])

Slicing for 2D arrays

In [26]:
A = np.arange(10,19).reshape(3,3)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [27]:
A[0,:]

array([10, 11, 12])

In [29]:
A[:,0]

array([10, 13, 16])

In [31]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

If the indexes of the rows or columns to be extracted are not contiguous, you can specify an array of
indexes

In [32]:
A[[0,2],0:2]

array([[10, 11],
       [16, 17]])

# Advanced Indexing:

1. Purely Integer Indexing:

 When integers are used for indexing. Each element of first dimension is paired with the element of the second dimension. So the index of the elements in this case are (0,0),(1,0),(2,1) and the corresponding elements are selected.

In [41]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a[[0,1,2],[0,0,1]]

array([1, 3, 6])

2. Boolean Indexing:

This indexing has some boolean expression as the index. Those elements are returned which satisfy that Boolean expression. It is used for filtering the desired element values.

In [47]:
c = np.array([10,40,80,50,100])
c

array([ 10,  40,  80,  50, 100])

In [49]:
# selecting nos. greater than 50

c[c>50]

array([ 80, 100])

In [50]:
# we wish to square the multiples of 40

c[c%40==0]**2

array([1600, 6400])

In [51]:
d = np.array([[5,5],[4,5],[16,4]])
d

array([[ 5,  5],
       [ 4,  5],
       [16,  4]])

In [55]:
d.sum(-1)

array([10,  9, 20])